[package]
name = "pir_onboard_led"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
embedded-hal = "1.0.0"
panic-halt = "1.0.0"
rp2040-hal = "0.11.0"   # check crates.io for latest

[profile.release]
opt-level = "s"

